### ISSUE TITLE
[Feature] Compatibility with the Heartache Mod? 

### ISSUE THREAD

**Issue by Coder-Relri** [efekos/FancyHealthBar#10]
Heartache Mod - (https://modrinth.com/mod/heartache)

The Heartache mod basically adds more heart types to your HUD, such as being set on fire or with the glowing effect. 
I think having both of these mods work together would be nice. In case compatibility can't be done from your side feel free to let me know and I'll try to ask the creator of the Heartache mod.

**Comment by efekos** [comment]
I want to add extra heart types to this mod itself, so having compatibility with another mod that does it would be kinda pointless as I would have to remove it later
