### ISSUE TITLE
[1.21.1] Wrong required minecraft version number

### ISSUE THREAD

**Issue by NumberSir** [efekos/FancyHealthBar#11]
required minecraft version in `fabric.mod.json` in `FancyHealthBar-1.1.1.jar` currently is `1.21`, which is supposed to be `1.21.1`

**Comment by efekos** [comment]
Latest version of the mod is supposed to be for only 1.21, looks like I forgot to remove 1.21.1 from version list while releasing the new version. I'll release a 1.21.1 port in a few minutes
