### ISSUE TITLE
[FEATURE] Custom sounds to FancyHealthBar 1.21

### ISSUE THREAD

**Issue by makumaku1974** [efekos/FancyHealthBar#2]
Could be a chaos to do though.

**Comment by efekos** [comment]
No, it isn't. And it doesn't look like easy to do so I probably won't add support for it.

**Comment by makumaku1974** [comment]
Actually is it possible for you to implement a custom sound config for your mod? I've already tested this mod and it is quite fancy hehe

**Comment by efekos** [comment]
It is possible, but I'm a terrible sound artist so I think that would need either a good website or someone else. Also, what do you exactly mean? like a configurable sound that plays when a heart spawns?

**Comment by makumaku1974** [comment]
> It is possible, but I'm a terrible sound artist so I think that would need either a good website or someone else. Also, what do you exactly mean? like a configurable sound that plays when a heart spawns?

Oh about custom sounds meaning any sounds can be played into it like using an OGG format.

-hurt sound
-heal sound

I think this two sound categories are better to configure. Heal sound is new since it hasnt been a minecraft feature yet,

**Comment by efekos** [comment]
I want to focus on heart animations and make them perfect before I move to other types of customization. Custom damage and heal sounds will definetly be considered later. I'm closing the issue for now, but I might re-open it once I feel ready to make it.
