### ISSUE TITLE
[Feature] Base Particle off of resource pack texture

### ISSUE THREAD

**Issue by TorchTheDragon** [efekos/FancyHealthBar#3]
Not sure how easy or hard this would be to implement, but it would make it look a bit smoother with some custom Hearts that people tend to use, like in my case.
![image](https://github.com/efekos/FancyHealthBar/assets/72819066/1549eeab-a773-41fc-8386-86a23d404d12)
I don't think red particles match well with non-binary hearts lol.

Just an idea though, otherwise I do like this mod 👍

**Comment by efekos** [comment]
Good idea, I will work on more customization for the next update.
