### ISSUE TITLE
[Link Issue] Can't use the Links in description for Discord or Patreon

### ISSUE THREAD

**Issue by TorchTheDragon** [efekos/FancyHealthBar#6]
No matter what, anytime I try to click on the links in the description it warns me about my privacy, here is the Discord one:
![image](https://github.com/user-attachments/assets/f1664328-961d-4e80-a2bb-147c82a594f5)

Here is what shows up when I hit "Help me understand"
![image](https://github.com/user-attachments/assets/c659bae6-6c3c-4900-96c7-cdcd99bc139a)

I have tried waiting on it though it seems like the issue is still occurring so I am starting to wonder if it may just possibly be an issue with the links.

**Comment by efekos** [comment]
Those links redirect to my website, which probably has it's certificate expired. I'll take a look at it today.
