### ISSUE TITLE
[Backport Request] Is it possible to make the mod available for 1.20.1?

### ISSUE THREAD

**Issue by ShyVaporeon** [efekos/FancyHealthBar#8]
I have a custom Vanilla++ modpack with 250 mods on 1.20.1 and this mod would fit in perfectly. 1.20.1 is still very popular for modding so I believe a lot of people would also benefit from this 🙏

**Comment by efekos** [comment]
https://www.curseforge.com/minecraft/mc-mods/fancy-health-bar/files/5668537
https://modrinth.com/mod/fancy-health-bar/version/1.1.1+1.20.1
